main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from marketplace import views as MarketplaceViews

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("", include("accounts.urls")),
    path("marketplace/", include("marketplace.urls")),
    path("search/", MarketplaceViews.search, name="search"),
    path("checkout/", MarketplaceViews.checkout, name="checkout"),
    path("", include("orders.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
import simplejson as json
from django.db import models
from accounts.models import User
from vendors.models import Food, Vendor

request_object = ""


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    transaction_id = models.CharField(max_length=100)
    amount = models.CharField(max_length=10)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.transaction_id


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(
        Payment, on_delete=models.SET_NULL, blank=True, null=True
    )
    vendors = models.ManyToManyField(Vendor, blank=True)
    order_number = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField(max_length=50)
    address = models.CharField(max_length=200)
    country = models.CharField(max_length=15)
    state = models.CharField(max_length=15)
    city = models.CharField(max_length=50)
    pin_code = models.CharField(max_length=10)
    total = models.FloatField()
    tax_data = models.JSONField(
        blank=True,
        help_text="Data format: {'tax_type':{'tax_percentage':'tax_amount'}}",
    )
    total_tax = models.FloatField()
    total_data = models.JSONField(blank=True, null=True)
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def order_placed_to(self):
        return ", ".join([str(i) for i in self.vendors.all()])

    def get_total_by_vendor(self):
        vendor = Vendor.objects.get(user=request_object.user)

        subtotal = 0
        tax = 0
        tax_dict = {}
        if self.total_data:
            total_data = json.loads(self.total_data)
            data = total_data.get(str(vendor.id))

            for key, value in data.items():
                subtotal += float(key)
                value = value.replace("'", '"')
                value = json.loads(value)
                tax_dict.update(value)

                for i in value:
                    for j in value[i]:
                        tax += float(value[i][j])

        grand_total = float(subtotal) + float(tax)

        data = {
            "subtotal": subtotal,
            "tax_dict": tax_dict,
            "grand_total": grand_total,
        }
        return data

    @property
    def name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.order_number


class OrderedFood(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(
        Payment, on_delete=models.SET_NULL, blank=True, null=True
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.food.food_name

accounts/forms.py
from django import forms
from .models import User, UserProfile
from .validators import allow_only_images_validator


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "username",
            "email",
            "phone_number",
            "password",
        ]

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match!")


class UserProfileForm(forms.ModelForm):
    profile_photo = forms.FileField(
        widget=forms.FileInput(attrs={"class": "btn btn-danger"}),
        validators=[allow_only_images_validator],
    )
    cover_photo = forms.FileField(
        widget=forms.FileInput(attrs={"class": "btn btn-danger"}),
        validators=[allow_only_images_validator],
    )
    latitude = forms.CharField(widget=forms.TextInput(attrs={"readonly": "readonly"}))
    longitude = forms.CharField(widget=forms.TextInput(attrs={"readonly": "readonly"}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            if field in self.Meta.not_required:
                self.fields[field].required = False
            else:
                self.fields[field].required = True

    class Meta:
        model = UserProfile
        fields = [
            "profile_photo",
            "cover_photo",
            "address",
            "latitude",
            "longitude",
            "country",
            "state",
            "city",
            "pin_code",
        ]
        not_required = [
            "cover_photo",
        ]


class UserInfoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["phone_number"].required = True

    class Meta:
        model = User
        fields = ["first_name", "last_name", "phone_number"]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Eieat | {% block title %}{% endblock title %}</title>
    <link rel="icon" type="image/x-icon" href="{% static "images/favicon.ico" %}">

    <!-- CSS -->
    <link href="{% static "css/iconmoon.css" %}" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet"> 
    <link href="{% static "css/cs-foodbakery-plugin.css" %}" rel="stylesheet">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="{% static "css/notification.css" %}" rel="stylesheet">
    <link href="{% static "css/custom.css" %}" rel="stylesheet">
    <link href="//cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" rel="stylesheet">
    
  </head>

  <body>
    <div class="wrapper">
        {% include "includes/header.html" %}

        {% block content %}
        {% endblock content %}

        {% include "includes/footer.html" %}
    </div>

    <!-- JAVASCRIPT -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'js/modernizr.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.all.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/js/all.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/functions.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'js/notify.min.js' %}"></script>
    <script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script>
      {% if messages %}
          {% for message in messages %}
              $.notify("{{message}}",{
                position:"top center",
                className:"{{message.tags}}",
                autoHideDelay: 5000,
              });
          {% endfor %}
      {% endif %}
    </script>
    <script>
      let table = new DataTable('#ordersTable');
    </script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Order Food Online{% endblock title %}
{% block content %}

<!-- Main Section Start -->
<div class="main-section">
  <!-- Home Pages Elements Strat -->
  <!-- Main Search Start -->
  <div
    class="page-section nopadding cs-nomargin"
    style="
      padding-top: 200px;
      padding-bottom: 150px;
      margin-bottom: 0px;
      background: url({% static "images/home-banner.jpg" %}) no-repeat center /
        cover;
    "
  >
    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div class="element-title">
            <h1
              style="
                font-size: 40px;
                color: #ffffff !important;
                text-transform: uppercase;
                line-height: 50px;
                margin-bottom: 25px;
                text-align: center;
              "
            >
              We are in the business of food<br />our restaurants do
            </h1>
            <p
              style="
                font-size: 18px;
                letter-spacing: 1px;
                color: #ffffff !important;
                text-align: center;
              "
            >
              Ridiculus sociosqu cursus neque cursus curae ante scelerisque
              vehicula.
            </p>
          </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div class="main-search fancy bg-holder">
            <form action="{% url "search" %}" method="GET" id="search_form">
              <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                  <div class="field-holder">
                    <span class="foodbakery-search-location-icon"
                            ><i class="icon-home3"></i
                          ></span>
                    <input type="text" placeholder="Resturant or Food name" name="keyword" />
                  </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                  <div class="field-holder">
                    <ul>
                      <li class="select-location">
                        <div
                          class="foodbakery-locations-fields-group foodbakery-focus-out"
                        >
                          <span class="foodbakery-search-location-icon"
                            ><i class="icon-location"></i
                          ></span>
                          <input
                            id="id_address"
                            type="text"
                            class="location-field-text filter"
                            placeholder="Location"
                            required
                            name="address"
                          />
                          <input type="hidden" name="lat" id="id_latitude" value=""/>
                          <input type="hidden" name="lon" id="id_longitude" value=""/>
                          <div id="autocomplete-suggestions"></div>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                  <div class="field-holder">
                    <span class="foodbakery-search-location-icon"
                            ><i class="fa-solid fa-location-arrow"></i></span>
                    <select class="text-uppercase" name="radius" autocomplete="off" required>
                      <option selected>Choose Radius</option>
                      <option value="5">5 km</option>
                      <option value="10">10 km</option>
                      <option value="20">20 km</option>
                      <option value="50">50 km</option>
                      <option value="75">75 km</option>
                      <option value="100">100 km</option>
                    </select>
                  </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12" style="padding-right: 0;">
                  <div class="field-holder">
                    <input type="submit" value="Search" />
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Main Search End -->

  <!-- Top Restarurants Section Start -->
  <div
    class="page-section nopadding cs-nomargin"
    style="
      margin-top: 0px;
      padding-top: 60px;
      padding-bottom: 0px;
      margin-bottom: 0px;
      background: #ffffff;
    "
  >
    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div class="element-title align-left">
            <h2>Top Restaurants</h2>
            <p>Explore restaurants, bars, and cafés by locality</p>
          </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div class="company-logo">
            <ul>
              {% for vendor in top_vendors %}
              <li class="has-border">
                <figure>
                  <a href="{% url "vendor_details" vendor.vendor_slug %}"
                    >
                  {% if vendor.user_profile.profile_photo %}
                  <img
                      src="{{vendor.user_profile.profile_photo.url}}"
                      class="attachment-full size-full wp-post-image"
                      alt=""
                  />
                  {% else %}
                  <img
                      src="{% static "images/vendor-default-profile-photo.png" %}"
                      class="attachment-full size-full wp-post-image"
                      alt=""
                  />
                  {% endif %}
                  </a>
                </figure>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Top Restarurants Section End -->
  <!-- Choose From Most Popular Listin Start -->
  <div
    class="page-section nopadding cs-nomargin"
    style="
      margin-top: 0px;
      padding-top: 60px;
      padding-bottom: 50px;
      margin-bottom: 0px;
      background: #ffffff;
    "
  >
    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div class="element-title align-center">
            <h2>Choose From New Restaurants</h2>
            <p>Felis portaest nisl arcu sit sollicitudin leo maximus euismod mi.</p>
          </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div class="listing fancy">
            <ul class="row">
              {% for vendor, categories in vendors.items %}
              <li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <div class="list-post featured">
                  <div class="img-holder">
                    <figure>
                      <a href="{% url "vendor_details" vendor.vendor_slug %}"
                        >
                      {% if vendor.user_profile.profile_photo %}
                      <img
                          src="{{vendor.user_profile.profile_photo.url}}"
                          class="attachment-full size-full wp-post-image"
                          alt=""
                      />
                      {% else %}
                      <img
                          src="{% static "images/vendor-default-profile-photo.png" %}"
                          class="attachment-full size-full wp-post-image"
                          alt=""
                      />
                      {% endif %}
                      </a>
                    </figure>
                    {% if vendor.is_open %}
                    <span class="restaurant-status open">
                        <em class="bookmarkRibbon"></em>Open
                    </span>
                    {% else %}
                    <span class="restaurant-status close">
                        <em class="bookmarkRibbon"></em>Closed
                    </span>
                    {% endif %}
                  </div>
                  <div class="text-holder">
                    <div class="post-title">
                      <h5>
                        <a href="{% url "vendor_details" vendor.vendor_slug %}">{{vendor.vendor_name}}</a>
                      </h5>
                    </div>
                    {% if categories %}
                    <ul class="ven-categories">
                    {% for category in categories %}
                        <li>{{category.category_name}}</li>
                    {% endfor %}
                    </ul>
                    {% endif %}
                  </div>
                </div>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Choose From Most Popular Listing End -->

  <!-- Home Pages Elements End  -->
</div>
<!-- Main Section End -->
{% endblock content %}